#!/bin/bash

PARAMS=$(echo "$@")

NAME="app"
ID=$(docker compose ps -q "$NAME")

if [ -z "$ID" ] || [ "$(docker compose ps -q "$NAME" --filter "status=running")" != "$ID" ]; then
    docker compose stop "$NAME" &> /dev/null
    docker compose rm -f "$NAME" &> /dev/null

    docker compose up -d --no-deps "$NAME" \
        --build \
        --entrypoint "sh" \
        -c "while true; do echo 'beep'; sleep 5; done" > /dev/null
fi

docker compose exec -T -u $UID:$GID $NAME $PARAMS
